Exception {msg: , stackTrace: [main(): none, getException(): Exception, foo(): Exception], errnoStr: }
